definitions:
  members.Member:
    properties:
      cohort:
        type: string
      createdAt:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone_number:
        type: string
      session1:
        type: boolean
      session1CompletionTime:
        type: string
      session2:
        type: boolean
      session2CompletionTime:
        type: string
      session3:
        type: boolean
      session3CompletionTime:
        type: string
      session4:
        type: boolean
      session4CompletionTime:
        type: string
      status:
        $ref: '#/definitions/members.Status'
      year:
        type: integer
    type: object
  members.Status:
    enum:
    - COMPLETE
    - INCOMPLETE
    type: string
    x-enum-varnames:
    - StatusComplete
    - StatusIncomplete
  users.Role:
    enum:
    - SUPERUSER
    - USER
    type: string
    x-enum-varnames:
    - SuperUserRole
    - UserRole
  users.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/users.Role'
    type: object
info:
  contact: {}
paths:
  /members:
    get:
      consumes:
      - application/json
      description: Get all fortify member
      parameters:
      - description: Cohort Year
        in: query
        name: year
        type: integer
      - description: Cohort
        in: query
        name: cohort
        type: string
      - description: Completion Status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/members.Member'
            type: array
        "400":
          description: Bad Request
      summary: Get all members
      tags:
      - members
    post:
      consumes:
      - application/json
      description: Create a single fortify member
      parameters:
      - description: First Name
        in: body
        name: first_name
        required: true
        schema:
          type: string
      - description: Last Name
        in: body
        name: last_name
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Cohort
        in: body
        name: cohort
        required: true
        schema:
          type: string
      - description: Year
        in: body
        name: year
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create a member
      tags:
      - members
  /members/{id}:
    delete:
      description: Delete a fortify member using member ID
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Delete a member
      tags:
      - members
    post:
      consumes:
      - application/json
      description: Update a fortify member using member ID
      parameters:
      - description: Member ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Update a member
      tags:
      - members
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a CSV file that contains fortify members
      parameters:
      - description: CSV file to upload
        in: formData
        name: uploadFile
        required: true
        type: file
      - description: Year
        in: query
        name: year
        required: true
        type: integer
      - description: Cohort
        in: query
        name: cohort
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Upload a file
      tags:
      - file-upload
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.User'
            type: array
        "400":
          description: Bad Request
      summary: Get all users
      tags:
      - users
  /users/{id}:
    delete:
      description: Delete a user using member ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Delete a user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Update user details and information
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Update a user
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Email to login
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password to login
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Login
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: Create user details and information
      parameters:
      - description: First Name
        in: body
        name: first_name
        required: true
        schema:
          type: string
      - description: Last Name
        in: body
        name: last_name
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create a user
      tags:
      - users
swagger: "2.0"
